"""
One-screen e-ink renderer for OutdoorGPT recipe mode.

Renders a finished recipe onto a Waveshare 7.5" (800x480) e-Paper HAT so the
cook can read it hands-free while the food is on the fire. The panel is
bistable: once drawn, the image stays put with the power off, so nobody has to
keep cranking just to hold the recipe on screen.

It also draws the instruction card (eink_instructions.png next to this file,
made by make_eink_instructions.py): at start-up, while the models are still
loading, and again on every press of the button. Pictures use the panel's
four grey levels; recipe text stays black on white.

Design goals
------------
* Never crash the voice agent. Every hardware / library problem is logged and
  swallowed; the conversation keeps going even with no panel attached.
* One screen only. The recipe prompt already asks the model to keep answers
  short, but we still auto-shrink the font until the whole thing fits 800x480 -
  there is no "page 2" a cook could scroll to without power.
* Off the hot path. The ~6 s SPI refresh runs in a daemon thread; if a newer
  recipe arrives while one is still drawing, the newest one wins.

Only the driver import and Pillow import happen lazily inside the methods, so
importing this module on a dev machine (or a Pi without the panel) is harmless.

Requires, on the Pi only:
    * Pillow            (pip install pillow)
    * waveshare_epd     (bundled in this repository as scripts/waveshare_epd,
                         a vendored copy of the Waveshare e-Paper driver)
"""

import os
import threading
import time

import device_settings
import spi_bus  # shared SPI lock (panel vs the HAT LEDs)

# Panel geometry (Waveshare 7.5" V2). The physical panel buffer is ALWAYS
# 800x480 (landscape) -- the driver has no concept of orientation. To show
# portrait text we render onto a rotated canvas and rotate the finished
# image back before handing it to the driver.
EPD_WIDTH = 800
EPD_HEIGHT = 480

# Orientation and rotation are per device (they depend on how the panel is
# mounted) and live in device_settings.py.
ORIENTATION = device_settings.EINK_ORIENTATION
ROTATE_DEGREES = device_settings.EINK_ROTATE_DEGREES

if ORIENTATION == "portrait":
    RENDER_WIDTH, RENDER_HEIGHT = EPD_HEIGHT, EPD_WIDTH   # 480 x 800
else:
    RENDER_WIDTH, RENDER_HEIGHT = EPD_WIDTH, EPD_HEIGHT   # 800 x 480

# The instruction card: a picture next to this file (any size; it is fitted
# to the screen), generated by make_eink_instructions.py. Name per device.
INSTRUCTIONS_IMAGE = device_settings.EINK_INSTRUCTIONS_IMAGE

# Pictures in the panel's 4-grey mode, or dithered to black and white.
GREYSCALE = getattr(device_settings, "EINK_GREYSCALE", True)
# The four levels exactly as the driver's 4-grey mode expects them (it
# compares for equality): black, dark grey, light grey, white.
GREY_LEVELS = (0x00, 0x80, 0xC0, 0xFF)
_GREY_LUT = [min(GREY_LEVELS, key=lambda lv: abs(lv - v)) for v in range(256)]

MARGIN = 16          # px kept clear on every side
LINE_SPACING = 1.18  # baseline-to-baseline as a multiple of the font size
MAX_FONT = 28        # largest body font we try, px
MIN_FONT = 13        # smallest we shrink to before truncating
TITLE_BUMP = 3       # the dish title is this many px larger than the body

# Candidate TTF fonts, in order of preference. If none exist we fall back to
# Pillow's built-in bitmap font (readable, just not as pretty).
_FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
]
_FONT_CANDIDATES_BOLD = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
]


def _first_existing(paths):
    for p in paths:
        if os.path.exists(p):
            return p
    return None


class EinkRecipeDisplay:
    """Lazily-initialised, fail-safe renderer for the recipe screen."""

    def __init__(self, verbose=False):
        self.verbose = verbose
        self._epd = None            # waveshare EPD instance, or None until first draw
        self._Image = None
        self._ImageDraw = None
        self._ImageFont = None
        self._font_path = _first_existing(_FONT_CANDIDATES)
        self._font_path_bold = _first_existing(_FONT_CANDIDATES_BOLD) or self._font_path
        self._first_draw = True
        self._init_failed = False   # once True we stop touching the hardware
        self._font_cache = {}       # (size, bold) -> font object
        self._lock = threading.Lock()
        self._pending = None        # newest text waiting to be drawn
        self._worker = None

    # ------------------------------------------------------------------ API

    def render_async(self, text):
        """Queue a recipe to be drawn, and return immediately.

        Only the most recent job matters: if a draw is already running, the new
        one replaces whatever was waiting, so the screen always ends on the
        latest thing asked for.
        """
        if text:
            self._queue(('text', text))

    def render_image_async(self, path=None):
        """Queue a picture to be drawn, and return immediately.

        path: anything Pillow opens; None means the instruction card next to
        this file. Fitted to the screen, centred, thresholded to black and
        white.
        """
        self._queue(('image', path))

    def render_blocking(self, text):
        """Render synchronously and RAISE on any error.

        For tests and one-off scripts (see scripts/test_eink.py) where you want
        to see failures. The live agent uses render_async instead, which is
        fail-safe and off the hot path.
        """
        self._ensure_ready()
        self._render_now(text)

    def render_image_blocking(self, path=None):
        """Draw a picture synchronously and RAISE on any error (see above)."""
        self._ensure_ready()
        self._render_image_now(path)

    def _queue(self, job):
        if self._init_failed:
            return
        with self._lock:
            self._pending = job
            if self._worker is not None and self._worker.is_alive():
                return  # the running worker will pick up self._pending
            self._worker = threading.Thread(target=self._drain, daemon=True)
            self._worker.start()

    def clear(self):
        """Blank the panel. Optional; not used by default (see full_reset)."""
        if self._init_failed:
            return
        try:
            self._ensure_ready()
            self._epd.init()
            self._epd.Clear()
            self._epd.sleep()
            self._first_draw = False
        except Exception as e:            # pragma: no cover - hardware only
            self._log(f"clear failed: {e}")

    # ------------------------------------------------------------- internals

    def _log(self, msg):
        if self.verbose:
            print(f"[eink] {msg}")

    def _drain(self):
        """Worker loop: draw the newest pending job until the queue is empty."""
        while True:
            with self._lock:
                job = self._pending
                self._pending = None
                if job is None:
                    return
            try:
                self._ensure_ready()
            except Exception as e:
                # Import / construct failed -> no usable panel. Stop trying so we
                # don't burn ~6 s per turn failing for the rest of the session.
                self._log(f"panel unavailable, disabling e-ink for this session: {e}")
                self._init_failed = True
                return
            kind, payload = job
            try:
                if kind == 'image':
                    self._render_image_now(payload)
                else:
                    self._render_now(payload)
            except Exception as e:
                # A transient draw error: log it but stay enabled; the next
                # job may well succeed.
                self._log(f"render failed (staying enabled): {e}")

    def _ensure_ready(self):
        """Import Pillow + the driver and construct the EPD. Raises on failure."""
        if self._Image is None:
            from PIL import Image, ImageDraw, ImageFont
            self._Image, self._ImageDraw, self._ImageFont = Image, ImageDraw, ImageFont
        if self._epd is None:
            from waveshare_epd import epd7in5_V2
            self._epd = epd7in5_V2.EPD()
            self._first_draw = True
            self._log("panel object created")

    def _load_font(self, size, bold=False):
        key = (size, bold)
        if key in self._font_cache:
            return self._font_cache[key]
        path = self._font_path_bold if bold else self._font_path
        if path:
            font = self._ImageFont.truetype(path, size)
        else:
            font = self._ImageFont.load_default()
        self._font_cache[key] = font
        return font

    def _text_width(self, draw, s, font):
        """Pixel width of `s`, across Pillow versions."""
        try:
            return draw.textlength(s, font=font)
        except AttributeError:
            pass
        try:
            return font.getlength(s)
        except AttributeError:
            bbox = draw.textbbox((0, 0), s, font=font)
            return bbox[2] - bbox[0]

    def _wrap_block(self, draw, text, font, max_width):
        """Word-wrap one logical line to a pixel width. Blank line stays blank."""
        if not text.strip():
            return [""]
        words = text.split()
        lines, cur = [], ""
        for w in words:
            trial = w if not cur else cur + " " + w
            if self._text_width(draw, trial, font) <= max_width or not cur:
                cur = trial
            else:
                lines.append(cur)
                cur = w
        if cur:
            lines.append(cur)
        return lines

    def _normalise(self, text):
        """Screen-friendly cleanup: keep line breaks, drop markdown / emoji noise."""
        import re
        text = text.replace("*", "").replace("#", "").replace("`", "")
        text = re.sub(r"[ \t]+", " ", text)              # collapse spaces within a line
        text = re.sub(r"\n[ \t]*\n[ \t]*\n+", "\n\n", text)  # cap blank runs at one
        emoji = re.compile(
            "[\U0001F300-\U0001FAFF\U00002700-\U000027BF\U0001F1E0-\U0001F1FF]+"
        )
        text = emoji.sub("", text)
        return [ln.rstrip() for ln in text.strip().split("\n")]

    def _layout(self, draw, raw_lines, size, max_width):
        """Wrap the whole recipe at a given body font size.

        Returns (items, total_height) where items is a list of
        (text, font, line_height). The first non-empty line is treated as the
        dish title: bold and a few px larger.
        """
        body = self._load_font(size, bold=False)
        title_size = size + TITLE_BUMP
        title = self._load_font(title_size, bold=True)

        items = []
        title_used = False
        for ln in raw_lines:
            is_title = (not title_used) and ln.strip() != ""
            font = title if is_title else body
            fsize = title_size if is_title else size
            line_h = int(fsize * LINE_SPACING)
            for wrapped in self._wrap_block(draw, ln, font, max_width):
                items.append((wrapped, font, line_h))
            if is_title:
                title_used = True
        total = sum(h for (_t, _f, h) in items)
        return items, total

    def _render_now(self, text):
        Image, ImageDraw = self._Image, self._ImageDraw
        # Layout happens in "render space" -- 480x800 for portrait,
        # 800x480 for landscape. Only at the very end do we rotate into the
        # panel's fixed 800x480 buffer.
        max_width = RENDER_WIDTH - 2 * MARGIN
        max_height = RENDER_HEIGHT - 2 * MARGIN
        raw_lines = self._normalise(text)

        img = Image.new("1", (RENDER_WIDTH, RENDER_HEIGHT), 255)  # 255 = white
        draw = ImageDraw.Draw(img)

        # Shrink the font until the whole recipe fits one screen.
        items = None
        size = MAX_FONT
        while size >= MIN_FONT:
            candidate, total = self._layout(draw, raw_lines, size, max_width)
            if total <= max_height:
                items = candidate
                break
            size -= 1

        # Even at the smallest size it overflows: keep what fits, add a marker.
        if items is None:
            size = MIN_FONT
            candidate, _ = self._layout(draw, raw_lines, size, max_width)
            kept, used = [], 0
            for it in candidate:
                if used + it[2] > max_height - int(MIN_FONT * LINE_SPACING):
                    break
                kept.append(it)
                used += it[2]
            marker = self._load_font(MIN_FONT)
            kept.append(("[...]", marker, int(MIN_FONT * LINE_SPACING)))
            items = kept
            self._log("recipe longer than one screen; truncated with a marker")

        y = MARGIN
        for wrapped, font, line_h in items:
            if wrapped:
                draw.text((MARGIN, y), wrapped, font=font, fill=0)  # 0 = black
            y += line_h

        self._push(img)
        self._log(f"drew recipe at {size}px in {len(items)} lines, orientation={ORIENTATION}")

    def _render_image_now(self, path=None):
        """Fit a picture onto the screen and draw it."""
        Image = self._Image
        path = path or INSTRUCTIONS_IMAGE
        if not os.path.isabs(path):
            path = os.path.join(os.path.dirname(os.path.abspath(__file__)), path)
        src = Image.open(path).convert("L")
        # Fit inside the render canvas, keeping the aspect ratio, centred.
        scale = min(RENDER_WIDTH / src.width, RENDER_HEIGHT / src.height)
        size = (max(1, round(src.width * scale)), max(1, round(src.height * scale)))
        if size != src.size:
            src = src.resize(size, Image.LANCZOS)
        offset = ((RENDER_WIDTH - size[0]) // 2, (RENDER_HEIGHT - size[1]) // 2)
        if GREYSCALE:
            # Snap every pixel to the nearest of the four levels. A smaller
            # picture is framed in its own corner colour, so its ground runs
            # to the edge of the screen instead of ending in a white border.
            src = src.point(_GREY_LUT)
            img = Image.new("L", (RENDER_WIDTH, RENDER_HEIGHT), src.getpixel((0, 0)))
            img.paste(src, offset)
            self._push(img, grey=True)
        else:
            img = Image.new("L", (RENDER_WIDTH, RENDER_HEIGHT), 255)
            img.paste(src, offset)
            self._push(self._dither(img))
        self._log(f"drew {os.path.basename(path)} at {size[0]}x{size[1]}, "
                  f"{'4 greys' if GREYSCALE else 'black and white'}, orientation={ORIENTATION}")

    def _dither(self, img):
        """Black and white with an ordered (Bayer) pattern, so a flat grey
        comes out as an even texture rather than noise. Without numpy, falls
        back to Pillow's error diffusion."""
        try:
            import numpy as np
        except ImportError:
            return img.convert("1")
        bayer = np.array([[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]],
                         dtype=np.float32)
        thresholds = (bayer + 0.5) / 16.0 * 255.0
        a = np.asarray(img, dtype=np.float32)
        h, w = a.shape
        t = np.tile(thresholds, (h // 4 + 1, w // 4 + 1))[:h, :w]
        return self._Image.fromarray(((a > t) * 255).astype(np.uint8)).convert("1")

    def _display_grey(self, panel_img):
        """The driver's 4-grey display with the pixel-to-plane step in numpy.

        epd7in5_V2.display_4Gray does the same job one pixel at a time in
        Python, which takes many seconds on the Pi. Same protocol: plane 0x10
        is set for black and light grey, plane 0x13 for black and dark grey,
        then refresh (0x12) and wait. Without numpy the driver's own path is
        used.
        """
        epd = self._epd
        epd.init_4Gray()
        try:
            import numpy as np
        except ImportError:
            epd.display_4Gray(epd.getbuffer_4Gray(panel_img))
            return
        a = np.asarray(panel_img.convert("L"), dtype=np.uint8)
        black, light, dark = a == 0x00, a == 0xC0, a == 0x80
        epd.send_command(0x10)
        epd.send_data2(np.packbits(black | light, axis=1).tobytes())
        epd.send_command(0x13)
        epd.send_data2(np.packbits(black | dark, axis=1).tobytes())
        epd.send_command(0x12)
        time.sleep(0.1)
        epd.ReadBusy()

    def _push(self, img, grey=False):
        """Rotate a render-space image into the panel buffer and draw it.

        grey: img is an "L" image holding only the four panel levels, drawn
        with the 4-grey mode. Otherwise img is 1-bit, black on white.
        """
        Image = self._Image
        if ORIENTATION == "portrait":
            panel_img = img.rotate(ROTATE_DEGREES, expand=True)
            # rotate(expand=True) can leave a canvas of the wrong exact size
            # due to rounding; paste onto a clean 800x480 canvas to be safe.
            if panel_img.size != (EPD_WIDTH, EPD_HEIGHT):
                canvas = Image.new(img.mode, (EPD_WIDTH, EPD_HEIGHT), 255)
                canvas.paste(panel_img, (0, 0))
                panel_img = canvas
        else:
            panel_img = img

        with spi_bus.LOCK:  # keep the LEDs off the bus while we draw
            try:
                if self._first_draw:
                    self._epd.init()
                    self._epd.Clear()        # one clean sweep on the very first draw
                    self._first_draw = False
                if grey:
                    self._display_grey(panel_img)   # its own init, for the grey mode
                else:
                    self._epd.init()         # wake from deep sleep (safe every draw)
                    self._epd.display(self._epd.getbuffer(panel_img))
            finally:
                # Always sleep, a failed draw included. init() starts the panel's
                # boost converter; without this the converter keeps running for
                # the rest of the session, and on crank power that standing load
                # is the difference between working and browning out. display()
                # does raise in practice: ReadBusy times out on a bad connection.
                try:
                    self._epd.sleep()        # bistable: image holds with the power off
                except Exception:
                    pass
